.TH simplecalc 1 "Januaray 2011"
.SH NAME
simplecalc \- a simple text based calculator
.SH SYNOPSIS
.B simplecalc
.RB [ \-i ]
.RB [ \-s 
.IR "file" ]
.RB [ \-z 
.IR "file" ]
.RB [ \-d ]
.RB [ \-- ]
.RB [ \-h ]
.RB [ \-v ]
.SH DESCRIPTION
.PP
XX
.PP
XX
.SH OPTIONS
.TP
.BR \-i ,\  --interactive
Go to Interactive mode (enabled by default).
.TP
.BI \-s\  file ,\ --script\  file
Process 
.I file 
and exit.
.TP
.BI \-z\  file ,\ --initialize\  file
.RI Initialize\ with\  file.
.TP
.BR \-d ,\  --debug
Enable debug output.
.TP
.BR \-- ,\  --ignore_rest
Ignore the rest of the labeled arguments following this flag.
.TP
.BR \-v\ --version
Display version information and exit.
.TP
.BR \-h ,\  --help
Display usage information and exit.
.SH EXAMPLES
.SH FILES
.PP
$HOME/X/XX/.bla.x
.SH BUGS
.SH AUTHOR
XX
